baseURL = "https://tlc-uva.github.io/educational-redesign-aid/"
publishDir = "docs"
languageCode = "en-us"
title = "Educational Redesign Aid"
theme = "TLC-UvA-theme"
defaultContentLanguage = "en"

[params]
  landingpageTitle = "Taking your teaching online"
  landingpageSubtitle = "The Teaching & Learning Centre developed an Educational Redesign Aid (ERA). Itâ€™s specifically designed to help you teach online."
  landingpageBannerImage = "images/landing-no-logo.jpg"
  landingpageLogoImage = "images/teaching-centre-landing.png"
  landingpageLogoImageSmall = "images/teaching-centre-hero.png"

  color = "#008bc1"

# [languages]
#   [languages.en]
#     languageName = "English"
#     title = "Educational Redesign Aid"
#     weight = 1
#   [languages.nl]
#     languageName = "Nederlands"
#     title = "Educational Redesign Aid"
#     weight = 2
